name: VIPcmds
author: HimbeersaftLP
main: himbeer\vipcmds\main
version: 1.0.0
api: 2.1.0
commands:
    vip:
        description: Main command
        usage: /vip gmc|gms|fly
        aliases: [premium]
permissions:
    vipcmds.vip:
        default: false
        description: Be a VIP
    vipcmds.gm:
        default: false
        description: Allow a VIP to use /vip gmc
    vipcmds.fly:
        default: false
        description: Allows a VIP to use /vip fly
